In [3]:
from concrete import fhe

table = fhe.LookupTable([x ** 2 for x in range(2 ** 4)])

@fhe.compiler({"x": "encrypted"})
def f(x):
    return table[x]

inputset = range(2 ** 4)
print(inputset)
circuit = f.compile(inputset)

x = 4

enc_x = circuit.encrypt(x)
enc_result = circuit.run(enc_x)
fhe_result = circuit.decrypt(enc_result)

print(f'FHE result {fhe_result}')

range(0, 16)
FHE result 16


In [10]:
import numpy as np
from concrete import fhe

weight = np.array([[2, 1], [3, 2]]).reshape(1, 1, 2, 2)
# print(weight)

@fhe.compiler({"x": "encrypted"})
def f(x):
    return fhe.conv(x, weight, strides=(2, 2), dilations=(1, 1), group=1)

inputset = [np.random.randint(0, 4, size=(1, 1, 4, 4)) for _ in range(10)]
circuit = f.compile(inputset)
print(inputset)
sample = np.array(
    [
        [3, 2, 1, 0],
        [3, 2, 1, 0],
        [3, 2, 1, 0],
        [3, 2, 1, 0],
    ]
).reshape(1, 1, 4, 4)

# print(sample)
enc_sampe = circuit.encrypt(sample)
enc_result = circuit.run(enc_sampe)
dec_result = circuit.decrypt(enc_result)

result = f(sample)
print(f'Results {result}')
print(f'Dec Results {dec_result}')
# circuit.encrypt_run_decrypt(sample)
# assert np.array_equal(circuit.encrypt_run_decrypt(sample), f(sample))

[array([[[[1, 2, 2, 1],
         [1, 1, 0, 1],
         [0, 2, 1, 2],
         [0, 3, 2, 2]]]]), array([[[[0, 1, 0, 3],
         [1, 3, 2, 0],
         [1, 2, 1, 3],
         [0, 3, 2, 0]]]]), array([[[[2, 0, 2, 2],
         [2, 0, 3, 3],
         [0, 3, 3, 3],
         [2, 3, 2, 3]]]]), array([[[[2, 0, 1, 3],
         [3, 1, 2, 1],
         [1, 0, 3, 0],
         [1, 3, 3, 1]]]]), array([[[[0, 3, 2, 1],
         [3, 1, 2, 1],
         [3, 2, 0, 1],
         [1, 2, 1, 2]]]]), array([[[[2, 3, 0, 1],
         [1, 1, 2, 1],
         [1, 2, 3, 2],
         [3, 0, 1, 0]]]]), array([[[[0, 2, 1, 1],
         [1, 3, 3, 3],
         [2, 1, 1, 0],
         [1, 3, 0, 3]]]]), array([[[[3, 1, 3, 1],
         [0, 0, 2, 0],
         [2, 1, 3, 0],
         [1, 1, 2, 0]]]]), array([[[[0, 2, 2, 0],
         [3, 2, 0, 3],
         [3, 2, 1, 0],
         [2, 1, 3, 0]]]]), array([[[[0, 3, 2, 1],
         [1, 1, 2, 1],
         [3, 0, 0, 2],
         [3, 1, 1, 2]]]])]
Results [[[[21  5]
   [21  5]]]]
Dec Re

In [11]:
import numpy as np
from concrete import fhe

@fhe.compiler({"x": "encrypted"})
def f(x):
    return fhe.maxpool(x, kernel_shape=(2, 2), strides=(2, 2), dilations=(1, 1))

inputset = [np.random.randint(0, 4, size=(1, 1, 4, 4)) for _ in range(10)]
circuit = f.compile(inputset)

sample = np.array(
    [
        [3, 2, 1, 0],
        [3, 2, 1, 0],
        [3, 2, 1, 0],
        [3, 2, 1, 0],
    ]
).reshape(1, 1, 4, 4)

result = f(sample)
print(f'Results {result}')


enc_sampe = circuit.encrypt(sample)
enc_result = circuit.run(enc_sampe)
dec_result = circuit.decrypt(enc_result)
print(f'Dec Results {dec_result}')

#assert np.array_equal(circuit.encrypt_run_decrypt(sample), f(sample))

Results [[[[3 1]
   [3 1]]]]
Dec Results [[[[3 2]
   [3 2]]]]


In [16]:
import numpy as np
from concrete import fhe

@fhe.compiler({"x": "encrypted", "y": "encrypted"})
def f(x, y):
    return fhe.array([x, y])

inputset = [(3, 2), (7, 0), (0, 7), (4, 2)]
circuit = f.compile(inputset)

sample = (3, 4)
assert np.array_equal(circuit.encrypt_run_decrypt(*sample), f(*sample))

In [18]:
from concrete import fhe
import numpy as np

@fhe.compiler({"x": "encrypted"})
def f(x):
    z = fhe.zero()
    return x + z

inputset = range(10)
circuit = f.compile(inputset)

for x in range(10):
    enc_sampe = circuit.encrypt(x)
    enc_result = circuit.run(enc_sampe)
    dec_result = circuit.decrypt(enc_result)
    print(f'Dec Results {dec_result}')
    #assert circuit.encrypt_run_decrypt(x) == x

Dec Results 0
Dec Results 1
Dec Results 2
Dec Results 3
Dec Results 4
Dec Results 5
Dec Results 6
Dec Results 7
Dec Results 8
Dec Results 9


In [19]:
from concrete import fhe
import numpy as np

@fhe.compiler({"x": "encrypted"})
def f(x):
    z = fhe.one()
    return x + z

inputset = range(10)
circuit = f.compile(inputset)

for x in range(10):
    enc_sampe = circuit.encrypt(x)
    enc_result = circuit.run(enc_sampe)
    dec_result = circuit.decrypt(enc_result)
    print(f'Dec Results {dec_result}')

Dec Results 1
Dec Results 2
Dec Results 3
Dec Results 4
Dec Results 5
Dec Results 6
Dec Results 7
Dec Results 8
Dec Results 9
Dec Results 10


In [20]:
from concrete import fhe
import numpy as np

@fhe.compiler({"x": "encrypted"})
def f(x):
    z = fhe.ones((2, 3))
    return x + z

inputset = range(10)
circuit = f.compile(inputset)

for x in range(10):
    enc_sampe = circuit.encrypt(x)
    enc_result = circuit.run(enc_sampe)
    dec_result = circuit.decrypt(enc_result)
    print(f'Dec Results {dec_result}')
    #assert np.array_equal(circuit.encrypt_run_decrypt(x), np.array([[x, x, x], [x, x, x]]) + 1)

Dec Results [[1 1 1]
 [1 1 1]]
Dec Results [[2 2 2]
 [2 2 2]]
Dec Results [[3 3 3]
 [3 3 3]]
Dec Results [[4 4 4]
 [4 4 4]]
Dec Results [[5 5 5]
 [5 5 5]]
Dec Results [[6 6 6]
 [6 6 6]]
Dec Results [[7 7 7]
 [7 7 7]]
Dec Results [[8 8 8]
 [8 8 8]]
Dec Results [[9 9 9]
 [9 9 9]]
Dec Results [[10 10 10]
 [10 10 10]]


In [26]:
from concrete import fhe
import numpy as np

@fhe.compiler({"x": "encrypted", "y":"encrypted", "z":"encrypted"})
def f(x, y, z):
    a = x | y
    b = y & z
    c = a ^ b
    return c

inputset = [
    (np.random.randint(0, 2**8), np.random.randint(0, 2**8), np.random.randint(0, 2**8))
    for _ in range(3)
]
print(inputset)
circuit = f.compile(inputset)

print(circuit)

[(119, 82, 19), (84, 39, 86), (140, 186, 4)]
%0 = x                          # EncryptedScalar<uint8>        ∈ [84, 140]
%1 = y                          # EncryptedScalar<uint8>        ∈ [39, 186]
%2 = z                          # EncryptedScalar<uint7>        ∈ [4, 86]
%3 = bitwise_or(%0, %1)         # EncryptedScalar<uint8>        ∈ [119, 190]
%4 = bitwise_and(%1, %2)        # EncryptedScalar<uint5>        ∈ [0, 18]
%5 = bitwise_xor(%3, %4)        # EncryptedScalar<uint8>        ∈ [101, 190]
return %5


In [27]:
@fhe.compiler({"x": "encrypted", "y": "encrypted", "z": "encrypted"})
def f(x, y, z):
    # hint that inputs should be considered at least 8-bits
    x = fhe.hint(x, bit_width=8)
    y = fhe.hint(y, bit_width=8)
    z = fhe.hint(z, bit_width=8)

    # hint that intermediates should be considered at least 8-bits
    a = fhe.hint(x | y, bit_width=8)
    b = fhe.hint(y & z, bit_width=8)
    c = fhe.hint(a ^ b, bit_width=8)

    return c

Compparison

In [32]:
import numpy as np
from concrete import fhe

def f(x, y):
    return x < y

inputset = [
    (np.random.randint(0, 2**4), np.random.randint(0, 2**4))
    for _ in range(100)
]

compiler = fhe.Compiler(f, {"x": "encrypted", "y": "encrypted"})
circuit = compiler.compile(inputset, show_mlir=True)

x = 3
y = 1
enc_sampe = circuit.encrypt(x, y)
enc_result = circuit.run(enc_sampe)
dec_result = circuit.decrypt(enc_result)
print(f'Dec Results {dec_result}')


MLIR
--------------------------------------------------------------------------------
module {
  func.func @main(%arg0: !FHE.eint<4>, %arg1: !FHE.eint<4>) -> !FHE.eint<1> {
    %cst = arith.constant dense<[0, 0, 0, 0, 4, 4, 4, 4, 8, 8, 8, 8, 12, 12, 12, 12]> : tensor<16xi64>
    %0 = "FHE.apply_lookup_table"(%arg0, %cst) : (!FHE.eint<4>, tensor<16xi64>) -> !FHE.eint<4>
    %cst_0 = arith.constant dense<[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]> : tensor<16xi64>
    %1 = "FHE.apply_lookup_table"(%arg1, %cst_0) : (!FHE.eint<4>, tensor<16xi64>) -> !FHE.eint<4>
    %2 = "FHE.add_eint"(%0, %1) : (!FHE.eint<4>, !FHE.eint<4>) -> !FHE.eint<4>
    %cst_1 = arith.constant dense<[0, 1, 1, 1, 2, 0, 1, 1, 2, 2, 0, 1, 2, 2, 2, 0]> : tensor<16xi64>
    %3 = "FHE.apply_lookup_table"(%2, %cst_1) : (!FHE.eint<4>, tensor<16xi64>) -> !FHE.eint<4>
    %cst_2 = arith.constant dense<[0, 4, 8, 12, 0, 4, 8, 12, 0, 4, 8, 12, 0, 4, 8, 12]> : tensor<16xi64>
    %4 = "FHE.apply_lookup_table"(%arg0, %cst_2)

Comparison strategies can be changed

In [33]:
import numpy as np
from concrete import fhe

configuration = fhe.Configuration(
    comparison_strategy_preference=fhe.ComparisonStrategy.ONE_TLU_PROMOTED,
)

def f(x, y):
    return x < y

inputset = [
    (np.random.randint(0, 2**4), np.random.randint(0, 2**4))
    for _ in range(100)
]

compiler = fhe.Compiler(f, {"x": "encrypted", "y": "encrypted"})
circuit = compiler.compile(inputset, configuration, show_mlir=True)


MLIR
--------------------------------------------------------------------------------
module {
  func.func @main(%arg0: !FHE.eint<5>, %arg1: !FHE.eint<5>) -> !FHE.eint<1> {
    %0 = "FHE.to_signed"(%arg0) : (!FHE.eint<5>) -> !FHE.esint<5>
    %1 = "FHE.to_signed"(%arg1) : (!FHE.eint<5>) -> !FHE.esint<5>
    %2 = "FHE.sub_eint"(%0, %1) : (!FHE.esint<5>, !FHE.esint<5>) -> !FHE.esint<5>
    %cst = arith.constant dense<[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]> : tensor<32xi64>
    %3 = "FHE.apply_lookup_table"(%2, %cst) : (!FHE.esint<5>, tensor<32xi64>) -> !FHE.eint<1>
    return %3 : !FHE.eint<1>
  }
}
--------------------------------------------------------------------------------



In [38]:
from concrete import fhe
import numpy as np

table = fhe.LookupTable([2, -1, 3, 0])

@fhe.compiler({"x": "encrypted"})
def f(x):
    sum = table[x] + table[x]
    return sum

inputset = [np.random.randint(0, 4, size=(2, 3)) for _ in range(10)]
print(inputset)
circuit = f.compile(inputset)

sample = [
    [0, 1, 3],
    [2, 3, 1],
]
expected_output = [
    [2, -1, 0],
    [3, 0, -1],
]
sample = np.array(sample)
enc_value = circuit.encrypt(sample)
enc_result = circuit.run(enc_value)
results_value = circuit.decrypt(enc_result)
print(f'results {results_value}')


# for i in range(2):
#     for j in range(3):
#         assert actual_output[i][j] == expected_output[i][j] == table[sample[i][j]]

[array([[1, 3, 3],
       [3, 1, 3]]), array([[2, 0, 2],
       [0, 1, 3]]), array([[3, 3, 0],
       [3, 3, 3]]), array([[3, 2, 1],
       [0, 3, 3]]), array([[2, 3, 0],
       [0, 1, 1]]), array([[0, 0, 2],
       [1, 0, 0]]), array([[3, 2, 0],
       [3, 2, 2]]), array([[2, 3, 0],
       [0, 2, 2]]), array([[0, 0, 2],
       [0, 2, 1]]), array([[1, 3, 1],
       [0, 0, 1]])]
results [[ 4 -2  0]
 [ 6  0 -2]]
