In [29]:
from concrete import fhe
import numpy as np
import torch
import torchvision
import torchvision.transforms as transforms
import time

from sklearn.model_selection import train_test_split

In [30]:
#device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [31]:
#hyperparams
no_epochs = 2
batch_size = 32
learning_rate = 0.001

In [32]:
#transform the dataset into tensors normalized range [-1, 1]
transform = transforms.Compose(
            [transforms.ToTensor(),
            transforms.Normalize((0.5),(0.5))     
        ])

In [33]:
#data sets downloading and reading
train_dataset = torchvision.datasets.MNIST(root='./data', 
                                        train=True,
                                        download=True,
                                        transform=transform
                                        )

test_dataset = torchvision.datasets.MNIST(root='data',
                                        train=False,
                                        download=True,
                                        transform=transform
                                        )

In [34]:
# Extract features (images) and labels from MNIST dataset
mnist_features = train_dataset.data.numpy().reshape(-1, 28, 28)
mnist_labels = train_dataset.targets.numpy()

# Reshape and expand dimensions to match the structure of load_digits dataset
x_train_mnist = np.expand_dims(mnist_features, 1)

# Split the MNIST data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(
    x_train_mnist, mnist_labels,  train_size=5000, test_size=100, shuffle=True, random_state=42
)

#x_train = x_train.astype('float64')
print(x_train.dtype)
print(x_train.shape)

print(x_train)
# plt.imshow(x_train[0,0], cmap='grey')
# plt.show()
# Verify the shapes
print("Shape of x_train from MNIST:", x_train.shape)
print("Shape of x_test from MNIST:", x_test.shape)
print("Shape of y_train from MNIST:", y_train.shape)
print("Shape of y_test from MNIST:", y_test.shape)

uint8
(5000, 1, 28, 28)
[[[[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]]


 [[[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]]


 [[[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]]


 ...


 [[[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]]


 [[[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]]


 [[[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]]]
Shape of x_train from MNIST: (5000, 1, 28, 28)
Shape of x_test from MNIST: (100, 1, 28, 28)
Shape of y_train from MNIST: (5000,)
Shape of y_test fro

In [35]:
@fhe.compiler({"image": "encrypted"})
def to_grayscale(image):
    with fhe.tag("scaling.r"):
        r = image[:, :, 0]
        r = (r * 0.30).astype(np.int64)

    with fhe.tag("combining.rgb"):
        gray = r 
        
    with fhe.tag("creating.result"):
        gray = np.expand_dims(gray, axis=2)
        result = np.concatenate((gray, gray, gray), axis=2)
    
    return result


In [36]:
configuration = fhe.Configuration(
    enable_unsafe_features=True,
    use_insecure_key_cache=True,
    insecure_key_cache_location=".keys",

    # To enable displaying progressbar
    show_progress=True,
    # To enable showing tags in the progressbar (does not work in notebooks)
    progress_tag=True,
    # To give a title to the progressbar
    progress_title="Evaluation:",
)

In [37]:
inputset = x_train
print(f"Compilation started @ {time.strftime('%H:%M:%S', time.localtime())}")
start = time.time()
circuit = to_grayscale.compile(inputset, configuration)
end = time.time()
print(f"(took {end - start:.3f} seconds)")

Compilation started @ 17:52:50
(took 0.996 seconds)


In [38]:
print(f"Key generation started @ {time.strftime('%H:%M:%S', time.localtime())}")
start = time.time()
circuit.keygen()
end = time.time()
print(f"(took {end - start:.3f} seconds)")

print()

Key generation started @ 17:52:51
(took 2.382 seconds)



In [40]:
image_data_b = x_train[0]
print(f"Evaluation started @ {time.strftime('%H:%M:%S', time.localtime())}")
start = time.time()
enc_image = circuit.encrypt(image_data_b)
enc_image = circuit.run(enc_image)
end = time.time()
print(f"(took {end - start:.3f} seconds)")

Evaluation started @ 17:52:56
(took 0.503 seconds)


In [98]:
@fhe.compiler({"x":"encrypted"})
def add(x):
    sum =  x[0,0,0] + x[0,0,0]
    return sum

In [101]:
@fhe.compiler({"x":"encrypted"})
def multiply(x):
    sum =  x[0,0,0] * x[0,0,0]
    return sum

In [ ]:
print(x_train)
x_train_a = x_train
sum = x_train_a[0][0][0][0] + x_train_a[0][0][0][1]
print(f'sum {sum}')

multiply = x_train_a[0][0][0][0] * x_train_a[0][0][0][1]
print(f'sum {multiply}')

In [105]:
x_train_a = x_train
circuit_add = add.compile(x_train_a)

enc_image = circuit_add.encrypt(x_train_a[0])
enc_image = circuit_add.run(enc_image)
dec_image = circuit_add.decrypt(enc_image)
print(dec_image)

0


In [106]:
circuit_multiply = multiply.compile(x_train_a)

# enc_image = circuit_multiply.encrypt(x_train_a[0])
enc_image = circuit_multiply.run(enc_image)
dec_image = circuit_multiply.decrypt(enc_image)
print(dec_image)